name: debug pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: install npm
        uses: ./.github/workflows/npm-install.yml
      - name: run eslint
        run: npm run eslint
