name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-install
      - name: run eslint
        run: npm run eslint

  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-install
      - name: run test
        run: npm run test

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-install
      - name: build application
        run: npm run build

  playwright-e2e-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  deploy:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' }}
    needs:
      - lint
      - unit-test
      - build
      - playwright-e2e-tests
    steps:
      - name: Trigger deployment
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: curl "$deploy_url"
  update-version:
    runs-on: ubuntu-20.04
    needs: [deploy]
    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
