name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/common-setup/npm-install.yml
    steps:
      - name: run eslint
        run: npm run eslint

  unit-test:
    uses: ./.github/workflows/common-setup/npm-install.yml
    steps:
      - name: run test
        run: npm run test

  build:
    uses: ./.github/workflows/common-setup/npm-install.yml
    steps:
      - name: build application
        run: npm run build

  playwright-e2e-tests:
    uses: ./.github/workflows/common-setup/npm-install.yml
    timeout-minutes: 60
    steps:
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
